version: "3.9"
services:
  app:
    build: .
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --debugger --reload

  db:
    build: ./postgres
    networks:
      app_net:
        ipv4_address: 172.30.0.100

    ports: 
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: example
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 8080:8080

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24