version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env

    command: flask run --host=0.0.0.0 --debugger --reload

  db:
    build: ./postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
